/**
 * Drill-down — go deeper on a single reasoning division.
 *
 * Generates more cross-domain prompts, more organon items,
 * and sub-questions derived from the division's guiding questions.
 */

import type { Division, LensResult } from './types.js';
import { reasoningDivisionsByTheme } from './data/divisions.js';
import { organonLists } from './data/organons.js';

/** Extended lens result with sub-questions for deeper exploration. */
export interface DrillResult extends LensResult {
  /** Sub-questions generated by contextualizing guiding questions */
  subQuestions: string[];
}

/**
 * Simple deterministic hash for seeding selection.
 */
function simpleHash(str: string): number {
  let h = 0;
  for (const c of str) h = ((h << 5) - h + c.charCodeAt(0)) | 0;
  return Math.abs(h);
}

/**
 * Pick N consecutive items from an array starting at a hash-derived index.
 */
function pickItems(items: string[], seed: number, count: number): string[] {
  const start = seed % items.length;
  const result: string[] = [];
  for (let i = 0; i < count; i++) {
    result.push(items[(start + i) % items.length]);
  }
  return result;
}

/**
 * Generate sub-questions by contextualizing each guiding question
 * with the problem and combining with organon concepts.
 */
function generateSubQuestions(division: Division, problem: string): string[] {
  const seed = simpleHash(division.theme + problem + 'drill');
  const snippet = problem.slice(0, 80);
  const subQuestions: string[] = [];

  // For each guiding question, generate a contextualized sub-question
  for (let i = 0; i < division.guidingQuestions.length; i++) {
    const gq = division.guidingQuestions[i];
    const phenomenaList = organonLists.find(l => l.id === 'phenomena')!;
    const phenomenon = phenomenaList.items[(seed + i * 7) % phenomenaList.items.length];

    subQuestions.push(
      `Regarding "${snippet}": ${gq} Consider this through the phenomenon of ${phenomenon}.`
    );
  }

  // Additional sub-questions from cross-pollinating with other divisions
  const otherThemes = [...reasoningDivisionsByTheme.keys()]
    .filter(t => t !== division.theme);
  const crossTheme1 = otherThemes[(seed + 3) % otherThemes.length];
  const crossTheme2 = otherThemes[(seed + 11) % otherThemes.length];
  const crossDiv1 = reasoningDivisionsByTheme.get(crossTheme1)!;
  const crossDiv2 = reasoningDivisionsByTheme.get(crossTheme2)!;

  subQuestions.push(
    `What would ${crossDiv1.theme} (${crossDiv1.binomen}) reveal about the ${division.theme.toLowerCase()} of "${snippet}"?`
  );
  subQuestions.push(
    `How does the perspective of ${crossDiv2.theme} challenge our ${division.theme.toLowerCase()} analysis of "${snippet}"?`
  );

  return subQuestions;
}

/**
 * Drill into a specific division — deeper analysis with more prompts and sub-questions.
 *
 * @param theme - Division theme name (e.g., 'ANALOGIES')
 * @param problem - The problem statement
 * @returns DrillResult with expanded analysis
 */
export function drill(theme: string, problem: string): DrillResult {
  const upper = theme.toUpperCase();
  const division = reasoningDivisionsByTheme.get(upper);
  if (!division) {
    throw new Error(
      `Unknown division theme: "${theme}". Available: ${[...reasoningDivisionsByTheme.keys()].join(', ')}`
    );
  }

  const seed = simpleHash(division.theme + problem);
  const snippet = problem.slice(0, 50);

  // Core question (same as standard)
  const coreQuestion = `${division.coreQuestion} — applied to: "${problem}"`;

  // Guiding questions (same as standard)
  const guidingQuestions = division.guidingQuestions;

  // EXPANDED: 8 items per organon list (vs 4 in standard)
  const relevantOrganonItems = organonLists.map(list => ({
    list: list.name,
    items: pickItems(list.items, seed + simpleHash(list.id), 8),
  }));

  // EXPANDED: 6 cross-domain prompts (vs 3 in standard)
  const sciencesList = organonLists.find(l => l.id === 'sciences')!;
  const phenomenaList = organonLists.find(l => l.id === 'phenomena')!;
  const activitiesList = organonLists.find(l => l.id === 'activities')!;

  const scienceItems = pickItems(sciencesList.items, seed, 4);
  const phenomenaItems = pickItems(phenomenaList.items, seed + 7, 3);
  const activityItems = pickItems(activitiesList.items, seed + 13, 2);

  const crossDomainPrompts: string[] = [
    `Consider ${division.theme} through the lens of ${scienceItems[0]} — what does ${scienceItems[0]} reveal about ${snippet}?`,
    `Consider ${division.theme} through the lens of ${scienceItems[1]} — what does ${scienceItems[1]} reveal about ${snippet}?`,
    `Consider ${division.theme} through the lens of ${scienceItems[2]} — what unique angle does ${scienceItems[2]} bring to ${snippet}?`,
    `Consider ${division.theme} through the phenomenon of ${phenomenaItems[0]} — how does ${phenomenaItems[0]} manifest in ${snippet}?`,
    `Consider ${division.theme} through the phenomenon of ${phenomenaItems[1]} — what patterns of ${phenomenaItems[1]} appear in ${snippet}?`,
    `Consider ${division.theme} through the activity of ${activityItems[0]} — what does the practice of ${activityItems[0]} teach us about ${snippet}?`,
  ];

  // NEW: Sub-questions for deeper exploration
  const subQuestions = generateSubQuestions(division, problem);

  return {
    division,
    coreQuestion,
    guidingQuestions,
    relevantOrganonItems,
    crossDomainPrompts,
    subQuestions,
  };
}
